#!/usr/bin/env bash
# clone-all.sh — clona i repo/tool GitHub della ricerca «Cerchi Vuoti» in repos/
# Idempotente: salta i repo gia presenti. Rilancia liberamente.
set -u
cd "$(dirname "$0")"
mkdir -p repos
cd repos
ok=0; skip=0; fail=0
clone() {
  local url="$1" dir="$2"
  if [ -d "$dir/.git" ]; then
    echo "  [skip] $dir (gia presente)"; skip=$((skip+1)); return
  fi
  echo "  [clone] $dir"
  if git clone --depth 1 "$url" "$dir" >/dev/null 2>&1; then
    ok=$((ok+1))
  else
    echo "  [FAIL]  $dir <- $url"; fail=$((fail+1))
  fi
}

echo "== World models — mondi interni & sogno predittivo =="
clone "https://github.com/danijar/dreamerv3.git" "danijar-dreamerv3"
clone "https://github.com/eloialonso/diamond.git" "eloialonso-diamond"
clone "https://github.com/facebookresearch/vjepa2.git" "facebookresearch-vjepa2"
clone "https://github.com/facebookresearch/jepa.git" "facebookresearch-jepa"
clone "https://github.com/etched-ai/open-oasis.git" "etched-ai-open-oasis"
clone "https://github.com/AlmondGod/tinyworlds.git" "almondgod-tinyworlds"
clone "https://github.com/nicklashansen/tdmpc2.git" "nicklashansen-tdmpc2"
clone "https://github.com/microsoft/mineworld.git" "microsoft-mineworld"
clone "https://github.com/NVIDIA/cosmos.git" "nvidia-cosmos"
clone "https://github.com/facebookresearch/ijepa.git" "facebookresearch-ijepa"
clone "https://github.com/nvidia-cosmos/cosmos-predict2.5.git" "nvidia-cosmos-cosmos-predict2.5"
clone "https://github.com/danijar/dreamerv2.git" "danijar-dreamerv2"
clone "https://github.com/OpenDriveLab/Vista.git" "opendrivelab-vista"
clone "https://github.com/1x-technologies/1xgpt.git" "1x-technologies-1xgpt"
clone "https://github.com/nvidia-cosmos/cosmos-transfer1.git" "nvidia-cosmos-cosmos-transfer1"

echo "== Coscienza — framework, teorie e indicatori =="
clone "https://github.com/wmayner/pyphi.git" "wmayner-pyphi"
clone "https://github.com/VersesTech/axiom.git" "versestech-axiom"
clone "https://github.com/youngbryan97/aura.git" "youngbryan97-aura"
clone "https://github.com/Steake/GodelOS.git" "steake-godelos"
clone "https://github.com/infer-actively/pymdp.git" "infer-actively-pymdp"
clone "https://github.com/giansha/Global-Workspace-Agents.git" "giansha-global-workspace-agents"
clone "https://github.com/Zuga-Technologies/zugamind.git" "zuga-technologies-zugamind"
clone "https://github.com/CognitiveComputingResearchGroup/lida-framework.git" "cognitivecomputingresearchgroup-lida-framework"
clone "https://github.com/BerenMillidge/FEP_Active_Inference_Papers.git" "berenmillidge-fep_active_inference_papers"
clone "https://github.com/rssmith33/Active-Inference-Tutorial-Scripts.git" "rssmith33-active-inference-tutorial-scripts"
clone "https://github.com/zfountas/deep-active-inference-mc.git" "zfountas-deep-active-inference-mc"
clone "https://github.com/Entropic-Science/qr-sampler.git" "entropic-science-qr-sampler"
clone "https://github.com/VersesTech/gameworld.git" "versestech-gameworld"

echo "== Inferenza attiva / predictive coding =="
clone "https://github.com/ReactiveBayes/RxInfer.jl.git" "reactivebayes-rxinfer.jl"
clone "https://github.com/NACLab/ngc-learn.git" "naclab-ngc-learn"
clone "https://github.com/conorheins/collective_motion_actinf.git" "conorheins-collective_motion_actinf"
clone "https://github.com/pni-lab/fep-attractor-network.git" "pni-lab-fep-attractor-network"
clone "https://github.com/coxlab/prednet.git" "coxlab-prednet"
clone "https://github.com/translationalneuromodeling/tapas.git" "translationalneuromodeling-tapas"
clone "https://github.com/ComputationalPsychiatry/pyhgf.git" "computationalpsychiatry-pyhgf"
clone "https://github.com/liukidar/pcx.git" "liukidar-pcx"
clone "https://github.com/thebuckleylab/jpc.git" "thebuckleylab-jpc"
clone "https://github.com/NACLab/self-revising-active-inference.git" "naclab-self-revising-active-inference"
clone "https://github.com/ComputationalPsychiatry/ActiveInference.jl.git" "computationalpsychiatry-activeinference.jl"
clone "https://github.com/spm/spm.git" "spm-spm"

echo "== Memoria degli agenti =="
clone "https://github.com/agiresearch/A-mem.git" "agiresearch-a-mem"
clone "https://github.com/bingreeky/MemGen.git" "bingreeky-memgen"
clone "https://github.com/em-llm/EM-LLM-model.git" "em-llm-em-llm-model"
clone "https://github.com/AIRI-Institute/AriGraph.git" "airi-institute-arigraph"
clone "https://github.com/mem0ai/mem0.git" "mem0ai-mem0"
clone "https://github.com/getzep/graphiti.git" "getzep-graphiti"
clone "https://github.com/letta-ai/letta.git" "letta-ai-letta"
clone "https://github.com/MemTensor/MemOS.git" "memtensor-memos"
clone "https://github.com/OSU-NLP-Group/HippoRAG.git" "osu-nlp-group-hipporag"
clone "https://github.com/Mirix-AI/MIRIX.git" "mirix-ai-mirix"
clone "https://github.com/lucidrains/titans-pytorch.git" "lucidrains-titans-pytorch"
clone "https://github.com/locuslab/open-unlearning.git" "locuslab-open-unlearning"
clone "https://github.com/topoteretes/cognee.git" "topoteretes-cognee"
clone "https://github.com/memodb-io/memobase.git" "memodb-io-memobase"
clone "https://github.com/kingjulio8238/Memary.git" "kingjulio8238-memary"

echo "== Artificial life / emergenza & auto-organizzazione =="
clone "https://github.com/Chakazul/Lenia.git" "chakazul-lenia"
clone "https://github.com/hunar4321/particle-life.git" "hunar4321-particle-life"
clone "https://github.com/hardmaru/WorldModelsExperiments.git" "hardmaru-worldmodelsexperiments"
clone "https://github.com/SakanaAI/asal.git" "sakanaai-asal"
clone "https://github.com/google-research/self-organising-systems.git" "google-research-self-organising-systems"
clone "https://github.com/flowersteam/adtool.git" "flowersteam-adtool"
clone "https://github.com/erwanplantec/FlowLenia.git" "erwanplantec-flowlenia"
clone "https://github.com/flowersteam/automated_discovery_of_lenia_patterns.git" "flowersteam-automated_discovery_of_lenia_patterns"
clone "https://github.com/CarperAI/OpenELM.git" "carperai-openelm"
clone "https://github.com/HackerPoet/Particle-Life.git" "hackerpoet-particle-life"
clone "https://github.com/PWhiddy/Growing-Neural-Cellular-Automata-Pytorch.git" "pwhiddy-growing-neural-cellular-automata-pytorch"
clone "https://github.com/tom-mohr/particle-life.git" "tom-mohr-particle-life"
clone "https://github.com/Transcenduality/primordis.git" "transcenduality-primordis"
clone "https://github.com/aidanbx/coralai.git" "aidanbx-coralai"
clone "https://github.com/shyamsn97/controllable-ncas.git" "shyamsn97-controllable-ncas"
clone "https://github.com/gengala/egnca.git" "gengala-egnca"

echo "== Architetture cognitive =="
clone "https://github.com/joonspk-research/generative_agents.git" "joonspk-research-generative_agents"
clone "https://github.com/anirudh9119/shared_workspace.git" "anirudh9119-shared_workspace"
clone "https://github.com/numenta/nupic-legacy.git" "numenta-nupic-legacy"
clone "https://github.com/nengo/nengo.git" "nengo-nengo"
clone "https://github.com/eloialonso/iris.git" "eloialonso-iris"
clone "https://github.com/joschabach/micropsi2.git" "joschabach-micropsi2"
clone "https://github.com/soartech/jsoar.git" "soartech-jsoar"
clone "https://github.com/mindpixel20/lida.git" "mindpixel20-lida"
clone "https://github.com/MineDojo/Voyager.git" "minedojo-voyager"
clone "https://github.com/daveshap/ACE_Framework.git" "daveshap-ace_framework"
clone "https://github.com/opencog/atomspace.git" "opencog-atomspace"
clone "https://github.com/asmaloney/ACT-R.git" "asmaloney-act-r"

echo "== Spaziale / robotica / embodied =="
clone "https://github.com/Genesis-Embodied-AI/genesis-world.git" "genesis-embodied-ai-genesis-world"
clone "https://github.com/huggingface/lerobot.git" "huggingface-lerobot"
clone "https://github.com/Physical-Intelligence/openpi.git" "physical-intelligence-openpi"
clone "https://github.com/NVIDIA/Isaac-GR00T.git" "nvidia-isaac-gr00t"
clone "https://github.com/nvidia-cosmos/cosmos-predict2.git" "nvidia-cosmos-cosmos-predict2"
clone "https://github.com/UMass-Embodied-AGI/3D-VLA.git" "umass-embodied-agi-3d-vla"
clone "https://github.com/isaac-sim/IsaacLab.git" "isaac-sim-isaaclab"
clone "https://github.com/openvla/openvla.git" "openvla-openvla"
clone "https://github.com/real-stanford/diffusion_policy.git" "real-stanford-diffusion_policy"
clone "https://github.com/mani-skill/ManiSkill.git" "mani-skill-maniskill"
clone "https://github.com/facebookresearch/habitat-lab.git" "facebookresearch-habitat-lab"
clone "https://github.com/ARISE-Initiative/robosuite.git" "arise-initiative-robosuite"
clone "https://github.com/RoboVerseOrg/RoboVerse.git" "roboverseorg-roboverse"
clone "https://github.com/allenai/ai2thor.git" "allenai-ai2thor"
clone "https://github.com/octo-models/octo.git" "octo-models-octo"
clone "https://github.com/robocasa/robocasa.git" "robocasa-robocasa"

echo "== Scena indie & builder solitari (fringe) =="
clone "https://github.com/joeynyc/hermes-hud.git" "joeynyc-hermes-hud"
clone "https://github.com/dancinlab/anima.git" "dancinlab-anima"
clone "https://github.com/269652/artificial-consciousness-blueprint.git" "269652-artificial-consciousness-blueprint"
clone "https://github.com/gaoxianglong/novaaware.git" "gaoxianglong-novaaware"
clone "https://github.com/joeynyc/hermes-hudui.git" "joeynyc-hermes-hudui"
clone "https://github.com/CONSTELLATION-ENGINE/constellation-engine.git" "constellation-engine-constellation-engine"
clone "https://github.com/stell2026/Anima.git" "stell2026-anima"
clone "https://github.com/ronniross/emergence-engine.git" "ronniross-emergence-engine"
clone "https://github.com/0thernes/cosmogonic-quantum-mechalogodrom.git" "0thernes-cosmogonic-quantum-mechalogodrom"
clone "https://github.com/phatware/recursive-consciousness.git" "phatware-recursive-consciousness"
clone "https://github.com/sklaff2a-gif/promethee-nexus.git" "sklaff2a-gif-promethee-nexus"
clone "https://github.com/daveshap/Claude_Sentience.git" "daveshap-claude_sentience"
clone "https://github.com/openinfer-project/openinfer.git" "openinfer-project-openinfer"
clone "https://github.com/lucasjinreal/Crane.git" "lucasjinreal-crane"
clone "https://github.com/dancinlab/hexa-lang.git" "dancinlab-hexa-lang"
clone "https://github.com/xigh/herbert-rs.git" "xigh-herbert-rs"
clone "https://github.com/arjunvad123/the-observer-hypothesis.git" "arjunvad123-the-observer-hypothesis"
clone "https://github.com/tetyah-prime/Seraph.git" "tetyah-prime-seraph"
clone "https://github.com/dancinlab/demiurge.git" "dancinlab-demiurge"
clone "https://github.com/dancinlab/hexa-chip.git" "dancinlab-hexa-chip"

echo "== Teoria di frontiera 2025-26 =="
clone "https://github.com/jennyzzt/dgm.git" "jennyzzt-dgm"
clone "https://github.com/facebookresearch/jepa-wms.git" "facebookresearch-jepa-wms"
clone "https://github.com/AI-ON/TheConsciousnessPrior.git" "ai-on-theconsciousnessprior"
clone "https://github.com/jennyzzt/awesome-open-ended.git" "jennyzzt-awesome-open-ended"
clone "https://github.com/ruflab/shimmer.git" "ruflab-shimmer"
clone "https://github.com/google-research/planet.git" "google-research-planet"
clone "https://github.com/ReactiveBayes/ReactiveMP.jl.git" "reactivebayes-reactivemp.jl"
clone "https://github.com/lemoz/darwin-godel-machine.git" "lemoz-darwin-godel-machine"

echo ""
echo "Fatto. clonati=$ok  saltati=$skip  falliti=$fail"
